export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_REQUEST_SUCCESS = "SIGNIN_REQUEST_SUCCESS";
export const SIGNIN_REQUEST_FAILURE = "SIGNIN_REQUEST_FAILURE";
export const SIGNOUT = "SIGNOUT";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_REQUEST_SUCCESS = "FETCH_USER_REQUEST_SUCCESS";
export const FETCH_USER_REQUEST_FAILURE = "FETCH_USER_REQUEST_FAILURE";
